# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(max_length=30)),
                ('u_enname', models.CharField(max_length=30, unique=True)),
                ('u_password', models.CharField(max_length=50)),
                ('u_email', models.EmailField(max_length=50)),
                ('u_role', models.IntegerField(default=1)),
                ('u_purview', models.IntegerField(default=2)),
                ('u_ctime', models.DateTimeField(auto_now_add=True)),
                ('u_mtime', models.DateTimeField(auto_now=True)),
                ('u_status', models.BooleanField(default=True)),
            ],
        ),
    ]
